namespace _02.FindTheDifference
{
    internal class Program
    {
        static void Main(string[] args)
        {
            /*
            You are given two strings "s" and "t".
            String "t" is generated by random shuffling string "s" and then add one more letter at a random position.
            Return the letter that was added to "t".
            */

            // Input 1:
            string s = "abcd";
            string t = "abcde";
            // Expected Output: e

            // Input 2:
            //string s = "";
            //string t = "y";
            // Expected Output: y

            // Input 3:
            //string s = "a";
            //string t = "aa";
            // Expected Output: a

            Console.WriteLine(FindTheDifference(s, t));
        }

        public static char FindTheDifference(string s, string t)
        {
            int sValue = 0;
            int tValue = 0;

            for (int i = 0; i < t.Length; i++)
            {
                tValue += t[i];

                if (i < s.Length)
                {
                    sValue += s[i];
                }
            }

            return (char)(tValue - sValue);
        }
    }
}